### ISSUE TITLE
Nice job, minor suggestion

### ISSUE THREAD

**Issue by jhconning** [pavkum/notable-todoist#1]
First of all, thanks for this excellent notable enhancement.   I don't understand much JS or CSS, but I was able to get it to run fairly easily.   I had just one minor suggestion to improve the documentation.

As written, the instructions tell the user to enter this in a code block in notable.
 ```
{
    "filter": "<any todoist valid filter">
  }
```
As a newbie, I found this step and the use of `<>` confusing at first. More useful perhaps would be to provide a concrete example and then explain that any other set of [todoist filters](https://todoist.com/help/articles/introduction-to-filters) can be invoked.  The example might include the `[]` to make clear it can be a list.  So the example could be:

````
```todoist
{
     "filter": ["all", "!subtask"]
  }
```
````

Thanks again!

**Comment by jhconning** [comment]
Also, is `filter` the only currently supported argument?   For example, asking for priority 1 items below does not seem to work for me.  Any plans to support such in the future? 
  
````
```todoist
{
 "filter": ["all", "!subtask"],
  "priority" : 1
}
```
````

**Comment by pavkum** [comment]
@jhconning Thanks for your suggestion :) 

I agree documentation needs to be improved a lot. I will add few more examples. As of now **filter** takes a string argument.

For example: 
1. today -> tasks having due date as today
2. today & p1 -> tasks having due date as today and priority p1
3. #Project -> get all tasks of project *Project* (project filter not working in the published version due to a bug. Already fixed. Will publish the changes soon)
etc

This is only a MVP. After the initial commit I have made a lot of improvements and currently in testing phase. You can expect an update in next couple of days. Please watch this space :) 

Feel free to reach out to me for any suggestions or issues or ERs

**Comment by pavkum** [comment]
@jhconning Have added support for sorting, grouping and have updated documentation with details. Please check it out. I'm closing the issue for now. Please feel free to reopen / create new one should you have doubts or need clarifications.
